### PR TITLE
Fix other issues

### PR DESCRIPTION
**Pull request by alexcrea**
I'm sorry to open another PR, but I found other issues

Notable changes:
f5fa77410fca8aea44e158fe39bfdd3aba7d5c28 "Repair cost reset" was not working on 1.21.1 as Disenchantment was using an outdated version of NBTEditor.
This commit remove the need of using NBTEditor and also remove NBTEditor and NBT class as now is not used.

acb9cac0dbfd21dcd50213eab3f4253aee4a8f2d Player#closeInventory reset cursor position of player to the center of the screen. 
Player#openInventory do close previous inventory properly. We do not need to manually call close when we open a new inventory. Doing this way the player's cursor will not move. 
It is probably the best option, as not moving the cursor every time an inventory open is probably more comfortable for most user.

04a3218b870ad6fa0e76b1c6441a6689e859f6c8 Add a scheduled task.

### CODE REVIEW

**Comment by alexcrea** [comment]
Do not merge yet, I just found another issue

**Comment by H7KZ** [comment]
added you as a collaborator, I trust you, so far your changes are good, you really take the time to go through the code and push the best solutions :D Not so like me that reviews & updates the code once a week on a free midnight session :DDDD

**Comment by alexcrea** [comment]
> added you as a collaborator, I trust you, so far your changes are good, you really take the time to go through the code and push the best solutions :D Not so like me that reviews & updates the code once a week on a free midnight session :DDDD

Thanks for trusting me !
I actually like the idea of this plugin, and discovered it trying to make my anvil plugin compatible with this one after an GitHub issue.

I may fix future issue only if I have time (currently on university summer vacation but will change soon)

I will publish 1.5.2 on GitHub bumping version on this pr and let you upload 1.5.2 on spigot.

**Comment by H7KZ** [comment]
Thanks a lot! I am too going to a university and right now have the summer break too :DD Fingers crossed everything will go well :)

Again, thanks a lot for maintaining this, I wouldn't even probably look at these problems till someone raised them in a issue xDD

Much love, bye!

**Pull request merged**
